# Generated by Django 2.2.7 on 2019-11-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='deleted',
            new_name='delete_tweet',
        ),
    ]
